In [1]:
import numpy as np

In [2]:
simple_list=[6,7,8]

In [3]:
np.array(simple_list)

array([6, 7, 8])

In [4]:
arr=np.array([2,4,5,6])

In [5]:
np.array([[1,2,3],[2,3,4],[4,5,6]])

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [6]:
np.arange(2,30)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.linspace(2,80,1000)

array([ 2.        ,  2.07807808,  2.15615616,  2.23423423,  2.31231231,
        2.39039039,  2.46846847,  2.54654655,  2.62462462,  2.7027027 ,
        2.78078078,  2.85885886,  2.93693694,  3.01501502,  3.09309309,
        3.17117117,  3.24924925,  3.32732733,  3.40540541,  3.48348348,
        3.56156156,  3.63963964,  3.71771772,  3.7957958 ,  3.87387387,
        3.95195195,  4.03003003,  4.10810811,  4.18618619,  4.26426426,
        4.34234234,  4.42042042,  4.4984985 ,  4.57657658,  4.65465465,
        4.73273273,  4.81081081,  4.88888889,  4.96696697,  5.04504505,
        5.12312312,  5.2012012 ,  5.27927928,  5.35735736,  5.43543544,
        5.51351351,  5.59159159,  5.66966967,  5.74774775,  5.82582583,
        5.9039039 ,  5.98198198,  6.06006006,  6.13813814,  6.21621622,
        6.29429429,  6.37237237,  6.45045045,  6.52852853,  6.60660661,
        6.68468468,  6.76276276,  6.84084084,  6.91891892,  6.996997  ,
        7.07507508,  7.15315315,  7.23123123,  7.30930931,  7.38

In [14]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(2,8)

array([[0.59161383, 0.59446159, 0.49589658, 0.57155527, 0.53757386,
        0.94215188, 0.04078632, 0.78012913],
       [0.37756129, 0.33631016, 0.49196813, 0.16930027, 0.64995954,
        0.87307396, 0.39848061, 0.36200808]])

In [16]:
np.random.randn(2,8)

array([[ 0.39231725, -0.12122214, -1.04786552, -0.11724694,  1.74747739,
         0.44455485, -0.23639445, -0.49394217],
       [-1.28330601,  0.65665886,  0.19299171, -1.1092768 ,  0.67849303,
        -1.9127113 ,  0.38864544,  2.04162175]])

In [17]:
np.random.randint(8,90)

76

In [18]:
sample_array=np.random.randint(50,66,10)

In [19]:
sample_array

array([65, 55, 65, 55, 59, 55, 61, 56, 58, 65])

In [20]:
sample_array.reshape(2,5)

array([[65, 55, 65, 55, 59],
       [55, 61, 56, 58, 65]])

In [21]:
sample_array.reshape(5,2)

array([[65, 55],
       [65, 55],
       [59, 55],
       [61, 56],
       [58, 65]])

In [22]:
sample_array.max()

65

In [23]:
sample_array.argmax()

0

In [24]:
a=np.eye(5)

In [25]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a=np.random.rand(2,3)

In [28]:
a

array([[0.89445248, 0.85519162, 0.55111287],
       [0.98957553, 0.77711224, 0.57234626]])

In [29]:
sample_array=np.arange(50,66)

In [30]:
sample_array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [31]:
sample_array[0]

50

In [32]:
sample_array[2]

52

In [33]:
sample_array[3:7]

array([53, 54, 55, 56])

In [34]:
sample_array[1:7]=100

In [35]:
sample_array

array([ 50, 100, 100, 100, 100, 100, 100,  57,  58,  59,  60,  61,  62,
        63,  64,  65])

In [36]:
subset_sample_array=sample_array[4:12]

In [37]:
subset_sample_array

array([100, 100, 100,  57,  58,  59,  60,  61])

In [38]:
sample_matrix=np.array([[2,3,4],[4,5,7],[6,78,9]])
sample_matrix

array([[ 2,  3,  4],
       [ 4,  5,  7],
       [ 6, 78,  9]])

In [39]:
sample_matrix[1,2]

7

In [40]:
sample_matrix[1,:]

array([4, 5, 7])

In [41]:
sample_matrix[2,:]

array([ 6, 78,  9])

In [42]:
sample_matrix[:,:]

array([[ 2,  3,  4],
       [ 4,  5,  7],
       [ 6, 78,  9]])

In [43]:
sample_matrix[:,1]

array([ 3,  5, 78])

In [44]:
sample_matrix[:,(1,2)]

array([[ 3,  4],
       [ 5,  7],
       [78,  9]])

In [45]:
sample_array

array([ 50, 100, 100, 100, 100, 100, 100,  57,  58,  59,  60,  61,  62,
        63,  64,  65])

In [46]:
sample_array+sample_array

array([100, 200, 200, 200, 200, 200, 200, 114, 116, 118, 120, 122, 124,
       126, 128, 130])

In [47]:
np.exp(sample_array)

array([5.18470553e+21, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 5.68572000e+24,
       1.54553894e+25, 4.20121040e+25, 1.14200739e+26, 3.10429794e+26,
       8.43835667e+26, 2.29378316e+27, 6.23514908e+27, 1.69488924e+28])

In [48]:
np.sqrt(sample_array)

array([ 7.07106781, 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        ,  7.54983444,  7.61577311,  7.68114575,
        7.74596669,  7.81024968,  7.87400787,  7.93725393,  8.        ,
        8.06225775])

In [49]:
np.log(sample_array)

array([3.91202301, 4.60517019, 4.60517019, 4.60517019, 4.60517019,
       4.60517019, 4.60517019, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727])

In [50]:
np.max(sample_array)

100

In [51]:
np.min(sample_array)

50

In [52]:
np.abs(sample_array)

array([ 50, 100, 100, 100, 100, 100, 100,  57,  58,  59,  60,  61,  62,
        63,  64,  65])

In [53]:
np.argmax(sample_array)

1

In [54]:
np.std(sample_array)

19.683332892322884

In [55]:
np.var(sample_array)

387.43359375

In [56]:
np.mean(sample_array)

74.9375

In [57]:
array=np.random.randn(4,5)

In [58]:
array

array([[ 1.63049635, -0.99528521,  0.39213404,  0.38711983, -1.13634336],
       [-0.63726021,  0.80946279,  1.193232  , -0.12967789, -0.21087301],
       [ 0.1913968 , -1.50479245,  0.78197525, -0.01912591,  0.71015117],
       [-0.46612427,  0.78481469, -1.87242237,  0.76103287,  1.13352312]])

In [59]:
np.round(array,decimals=2)

array([[ 1.63, -1.  ,  0.39,  0.39, -1.14],
       [-0.64,  0.81,  1.19, -0.13, -0.21],
       [ 0.19, -1.5 ,  0.78, -0.02,  0.71],
       [-0.47,  0.78, -1.87,  0.76,  1.13]])

In [60]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
a3.ndim

3

In [62]:
a3.shape

(3, 3, 3)